import Navbar from "../components/navbar";
import Head from "next/head";

function CreateRecipes() {
  return (
    <>
      <Head>
        <title>Create Recipes</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Navbar />
      <div className="bg-gray-800 flex flex-col justify-center pt-36">
        <form
          className="max-w-[400px] w-full mx-auto bg-gray-900 p-8 px-8 rounded-lg"
          action="/api/createRecipes"
          method="post"
        >
          <h2 className="text-4xl text-white font-bold text-center">
            Personal Recipes
          </h2>
          <div className="flex flex-col text-gray-400 py-2">
            <label>Title</label>
            <input
              className="rounded-lg bg-gray-700 mt-2 p-2 focus:border--blue-500 focus:bg-gray-800 focus:outline-none h-9"
              name="title"
              type="text"
            />
          </div>
          <div className="flex flex-col text-gray-400 py-2">
            <label>Serving Size</label>
            <input
              className="rounded-lg bg-gray-700 mt-2 p-2 focus:border--blue-500 focus:bg-gray-800 focus:outline-none"
              name="servingSize"
              type="text"
            />
          </div>
          <div className="flex flex-col text-gray-400 py-2">
            <label>Ingredients</label>
            <input
              className="rounded-lg bg-gray-700 mt-2 p-2 focus:border--blue-500 focus:bg-gray-800 focus:outline-none"
              name="ingredients"
              type="text"
            />
          </div>
          <div className="flex flex-col text-gray-400 py-2">
            <label>Instructions</label>
            <input
              className="rounded-lg bg-gray-700 mt-2 p-2 focus:border--blue-500 focus:bg-gray-800 focus:outline-none"
              name="instructions"
              type="text"
            />
          </div>
          <div className="flex flex-col text-gray-400 py-1 text-center">
            <button className="border rounded-xl bg-teal-500 w-full p-1 my-5 hover:bg-teal-400 text-white">
              Save
            </button>
          </div>
        </form>
      </div>
    </>
  );
}

export default CreateRecipes;
