import Head from "next/head";
import Sidebar from "../components/sidebar";
import { useState, useEffect } from "react";
import axios from "axios";
import Recipes from "../components/favoritesCards";

function Favorites() {
  const [data, setData] = useState("");

  useEffect(() => {
    getFavorites();
  }, []);
  const options = {
    method: "Get",
    url: "/api/favorites",
  };
  const getFavorites = (e) => {
    axios.request(options).then(function (res) {
      setData(res.data);
      console.log(data);
    });
  };

  return (
    <>
      <Head>
        <title>Recipes</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Fuzzy Bubbles"
        />
      </Head>
      <Sidebar />
      <h1 className="text-center text-teal-500 font-bold text-4xl pt-10 underline">
        My Very Own Recipes
      </h1>
      <div className=" flex flex-wrap items-center justify-center  w-full m-auto pt-4 text-white z-10">
        <Recipes data={data} />
      </div>
    </>
  );
}

export default Favorites;
