import Head from "next/head";
import Navbar from "../components/navbar";
import { useState, useEffect } from "react";
import axios from "axios";
import Recipes from "../components/favoritesCards";

function Favorites() {
  const [data, setData] = useState("");

  useEffect(() => {
   getFavorites();
  }, []);
  const options = {
    method: "GET",
    url: "/api/favorites",
  };
  const getFavorites = async () => {
     await axios.request(options).then(function (res) {
      setData(res.data);
      console.log(data);
    });
  };

  return (
    <>
      <Head>
        <title>Favorites</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Navbar />
      <h1 className="text-center text-teal-500 font-bold text-4xl pt-24 pb-28 underline">
        My Very Own Recipes
      </h1>
      <div className=" flex flex-wrap items-center justify-center  w-full m-auto  ">
        <Recipes data={data} />
      </div>
    </>
  );
}

export default Favorites;
